import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { extname, relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const dist = resolve(root, "dist");
const output = resolve(root, "convex", "staticAssets.ts");

const contentTypes = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
};

async function filesIn(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map((entry) => {
    const path = resolve(directory, entry.name);
    return entry.isDirectory() ? filesIn(path) : [path];
  }));
  return nested.flat();
}

const assets = [];
for (const file of await filesIn(dist)) {
  const relativePath = relative(dist, file).split("\\").join("/");
  const route = relativePath === "index.html" ? "/" : `/${relativePath}`;
  const bodyBase64 = (await readFile(file)).toString("base64");
  assets.push({
    path: route,
    contentType: contentTypes[extname(file)] ?? "application/octet-stream",
    bodyBase64,
    immutable: route.startsWith("/assets/"),
  });
}

const source = [
  "// Generated by scripts/embed-static.mjs. Do not edit by hand.",
  `export const staticAssets = ${JSON.stringify(assets, null, 2)} as const;`,
  "",
].join("\n");

await mkdir(resolve(root, "convex"), { recursive: true });
await writeFile(output, source);
console.log(`Embedded ${assets.length} static assets for Convex HTTP actions.`);
